# Tomcat 9.0 띄우기

version: "3.8"

services:
  was:
    image: tomcat:9.0
    container_name: tomcat-server
    ports:
      - "8080:8080"
    volumes:
      - ~/tomcat/webapps:/usr/local/tomcat/webapps  # Host(Aws):Container