version: "3.8"

services:

  tomcat-was:  # 서비스 tomcat-was
    image: tomcat:9.0
    container_name: tomcat-server
    ports:
      - "8080:8080"
    volumes:
      - ~/tomcat/webapps:/usr/local/tomcat/webapps
    networks:
      - server-net

  nginx-proxy:  # 서비스 nginx-proxy
    image: nginx:latest
    container_name: nginx-server
    ports:
      - "80:80"
    volumes:
      - ~/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - server-net
    depends_on:
      - tomcat-was

networks:
  server-net:
    driver: bridge